# Generated by Django 5.1.5 on 2025-05-22 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguardando_aprovacao', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('separado', 'Separado'), ('entregue', 'Entregue')], default='aguardando_aprovacao', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
