# gestao_patrimonial/settings.py

"""
Django settings for gestao_patrimonial project.
Generated by 'django-admin startproject' using Django 5.1.5.
"""

import os
from pathlib import Path
import dj_database_url

# ------------------------------------------------------------------------------
# Caminho base do projeto
# ------------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------------------
# Segurança
# ------------------------------------------------------------------------------
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-local-secret-key')
DEBUG = os.environ.get('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# ------------------------------------------------------------------------------
# Configuração de arquivos estáticos (static files)
# ------------------------------------------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
os.makedirs(BASE_DIR / "static", exist_ok=True)

# ------------------------------------------------------------------------------
# Configuração de arquivos de mídia (media files)
# ------------------------------------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
os.makedirs(MEDIA_ROOT, exist_ok=True)

# ------------------------------------------------------------------------------
# Internacionalização
# ------------------------------------------------------------------------------
LANGUAGE_CODE = 'pt-br'
# TIME_ZONE = 'America/Sao_Paulo'  # opcional se quiser definir fuso
# USE_I18N = True
# USE_L10N = True
# USE_TZ = True

# ------------------------------------------------------------------------------
# Configuração dos templates
# ------------------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
            BASE_DIR / "interface" / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'builtins': [
                "core.templatetags.saldo",
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ------------------------------------------------------------------------------
# Apps instalados
# ------------------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',

    'core',
    'interface',
]

# ------------------------------------------------------------------------------
# Middleware
# ------------------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ------------------------------------------------------------------------------
# URL Configuration
# ------------------------------------------------------------------------------
ROOT_URLCONF = 'gestao_patrimonial.urls'

# ------------------------------------------------------------------------------
# WSGI Application
# ------------------------------------------------------------------------------
WSGI_APPLICATION = 'gestao_patrimonial.wsgi.application'

# ------------------------------------------------------------------------------
# Banco de Dados: configuração PostgreSQL local (padrão)
# ------------------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'gestao_utf8'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', '123'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    }
}

# Se preferir usar DATABASE_URL (Heroku, .env, Render etc.), descomente abaixo:
# DATABASES = {
#     'default': dj_database_url.parse(
#         os.environ.get(
#             'DATABASE_URL',
#             'postgres://postgres:123@localhost:5432/gestao_utf8'
#         ),
#         conn_max_age=600,
#         ssl_require=bool(os.environ.get('DATABASE_SSL', False)),
#     )
# }

# ------------------------------------------------------------------------------
# Configuração mínima do Django REST Framework
# ------------------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

# ------------------------------------------------------------------------------
# Campo padrão para chaves primárias
# ------------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------------------------------------------------------
# Configuração de login e URLs de redirecionamento
# ------------------------------------------------------------------------------
LOGIN_REDIRECT_URL = 'lista_produtos'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# ------------------------------------------------------------------------------
# Modelo de usuário customizado
# ------------------------------------------------------------------------------
AUTH_USER_MODEL = 'core.Usuario'

# ------------------------------------------------------------------------------
# Chave da API Cosmos (exemplo; mover para env em produção)
# ------------------------------------------------------------------------------
COSMOS_API_KEY = os.environ.get('COSMOS_API_KEY', 'your-cosmos-api-key')
